version: '3.8'

services:
  escala-midia:
    build: .
    container_name: app_escala_midia
    ports:
      - "8080:8080"
    volumes:
      # Isso garante que seu banco de dados não seja apagado se o container reiniciar
      - ./db.sqlite3:/app/db.sqlite3 
    restart: unless-stopped