# Generated by Django 6.0.4 on 2026-04-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Culto de Domingo, Santa Ceia', max_length=100)),
                ('data', models.DateTimeField()),
                ('vagas_midia', models.IntegerField(default=2, help_text='Quantas pessoas precisam servir neste dia?')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('funcao_principal', models.CharField(choices=[('camera', 'Câmera'), ('som', 'Mesa de Som'), ('projecao', 'Projeção / Letras'), ('geral', 'Apoio Geral')], default='geral', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.evento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.membro')),
            ],
            options={
                'unique_together': {('evento', 'membro')},
            },
        ),
    ]
