# Generated by Django 6.0.4 on 2026-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.CharField(choices=[('camera', 'Câmera'), ('story', 'Story'), ('projecao', 'Projeção / Letras'), ('geral', 'Apoio Geral')], default='geral', max_length=20),
        ),
        migrations.AlterField(
            model_name='membro',
            name='funcao_principal',
            field=models.CharField(choices=[('camera', 'Câmera'), ('story', 'Story'), ('projecao', 'Projeção / Letras'), ('geral', 'Apoio Geral')], default='geral', max_length=20),
        ),
    ]
